### PR TITLE
Nightly Toolchain Note

### PR DESCRIPTION
**Pull request by coltonhurst**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add a note about the required nightly toolchain. Without this people will receive an error when attempting to run the `build-api.sh` script.

For posterity, the nightly toolchain is required for certain features deemed unsafe. You can find more info here: https://github.com/bitwarden/sdk/pull/512

## Code changes

- **README.md:** Add nightly install instructions

## Before you submit

- Please add **unit tests** where it makes sense to do so

### CODE REVIEW

**Review by dani-garcia — DISMISSED** [review]
LGTM, we can also consider running `rustup toolchain install nightly` inside the script directly, as it's pretty fast when the nightly toolchain is already installed.

**Comment by coltonhurst** [comment]
> LGTM, we can also consider running `rustup toolchain install nightly` inside the script directly, as it's pretty fast when the nightly toolchain is already installed.

Fair. Is there a pattern or precedence set in other crates that use nightly commands in scripts? I personally like installing toolchains manually but I'm totally fine either way.

**Comment by dani-garcia** [comment]
I know `cross` does at least, when running `cross build -p bitwarden-uniffi --release --target=aarch64-linux-android` to build the android SDK, it will install the `stable-x86_64-unknown-linux-gnu` to run the build under docker.

**Comment by coltonhurst** [comment]
> I know `cross` does at least, when running `cross build -p bitwarden-uniffi --release --target=aarch64-linux-android` to build the android SDK, it will install the `stable-x86_64-unknown-linux-gnu` to run the build under docker.

Good point. I have moved it to the script & updated the readme in this commit: [567f1db](https://github.com/bitwarden/sdk/pull/675/commits/567f1dba1635812aa5c9171f1a44c1143b861b71)

**Review by dani-garcia — COMMENTED** [review]
The lint CI is failing, you need to run `npm run prettier` because the readme changes are exceeding the line wrapping

**Review by dani-garcia — APPROVED** [review]

**Pull request merged**
