### PR TITLE
Offer Maven package at SDK repository

### PR DESCRIPTION
**Pull request by withinfocus**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [X] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Publishes the Maven artifact to the SDK repository vs. the spinoff private one just for that purpose.

## Code changes

- **languages/kotlin/sdk/build.gradle:** Path change.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)

### CODE REVIEW

**Comment by Hinton** [comment]
We need to do a few more changes for this to work.

- Rename sdk to contain mobile or kotlin.
- Remove PAT
- Ideally update snapshot naming to be `last-version-snapshot`. since snapshots keep all old versions resulting in large sizes. We'll want a way to delete older snapshots.
- Configure artifacts cleanup for non tagged versions.

**Comment by withinfocus** [comment]
> We need to do a few more changes for this to work.
> 
> * Rename sdk to contain mobile or kotlin. Since it's going to collide with the java version.

Done.

> * Remove PAT

Not sure why we'd remove the token access as this is needed to publish to Packages.

> * Ideally update snapshot naming to be `last-version-snapshot`. since snapshots keep all old versions resulting in large sizes. We'll want a way to delete older snapshots.

Pushed a commit that uses non-snapshot versioning for `master` pushes, otherwise use the version and branch name with a snapshot otherwise. Is this what you're wanting?

> * Configure artifacts cleanup for non tagged versions.

Do we want to automate this across the whole repo?

**Comment by withinfocus** [comment]
https://github.com/bitwarden/sdk/packages/1945815

**Comment by Hinton** [comment]
Replaced with https://github.com/bitwarden/sdk/pull/235

**Comment by withinfocus** [comment]
You can always make commits directly to this branch vs. new branch and PR creation.

**Pull request closed without merging**
