### PR TITLE
[SM-1399] Update the README for Windows on ARM

### PR DESCRIPTION
**Pull request by coltonhurst**
## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/SM-1399

## 📔 Objective

Just `cargo build` is not sufficient for building the SDK on Windows on ARM. We should add clarity to what is required so that `cargo build` will run successfully.

Python is required. Clang is also required for [ring](https://crates.io/crates/ring) (more info [here](https://github.com/briansmith/ring/blob/main/BUILDING.md)).

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation
  team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed
  issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Review by dani-garcia — COMMENTED** [review]
I didn't see the Python requirement in the ring docs, but yeah the clang requirement is true.

Rather than full visual studio I think we can recommend installing the [Visual Studio Build Tools](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2022) which should be somewhat lighter than a full visual studio install. You still need to manually select the `clang` component and add it to the PATH though.

**Comment by coltonhurst** [comment]
> I didn't see the Python requirement in the ring docs, but yeah the clang requirement is true.
> 
> Rather than full visual studio I think we can recommend installing the [Visual Studio Build Tools](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2022) which should be somewhat lighter than a full visual studio install. You still need to manually select the `clang` component and add it to the PATH though.

Do we know if those build tools include Clang? I attempted this the first time around in my tests and I couldn't find Clang in the filesystem until after I installed the full suite.

I would much rather only recommend Build Tools because it is much smaller as you mentioned.

**Comment by dani-garcia** [comment]
I think for both the build tools and the full visual studio package you have to manually select `clang` from the optional packages list inside the `Visual Studio Installer`, but I haven't checked.

**Comment by dani-garcia** [comment]
I think that's the wrong download, that is the runtime redist and not the build tools, this is what i get with the build tools:
Screenshot 2024-08-07 at 18 46 36
Screenshot 2024-08-07 at 18 50 04

**Comment by coltonhurst** [comment]
> I think that's the wrong download, that is the runtime redist and not the build tools, this is what i get with the build tools: [image]

Ah, I did have the wrong download. Thanks @dani-garcia!

Updated in https://github.com/bitwarden/sdk/pull/942/commits/941fbaea845162e1eb8b6242bf2a2d0a594dbb85

**Review by dani-garcia — APPROVED** [review]

**Pull request merged**
