### PR TITLE
[SM-1153] Part 1 Secrets sync | Generate API bindings

### PR DESCRIPTION
**Pull request by Thomas-Avery**
## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Expose the new secrets sync endpoint.

Server PR  https://github.com/bitwarden/server/pull/3906

## Code changes

ran the command `./support/build-api.sh`

## Before you submit

- Please add **unit tests** where it makes sense to do so

### CODE REVIEW

**Comment by Thomas-Avery** [comment]
The command `./support/build-api.sh` replaces `crates/bitwarden-api-api/Cargo.toml` and `crates/bitwarden-api-identity/Cargo.toml`. 

I reverted the changes for the `Cargo.toml` files. 

I did notice the replacements had an extra dependency `serde_with = "^2.0"` do we need this included in the `Cargo.toml` files?

**Comment by dani-garcia** [comment]
Yeah for the moment the Cargo.toml changes need to be reverted manually. Thankfully those two files don't need to change very often outside of version bumps. 

The generated bindings aren't using the `serde_with` crate so it doens't need to be included.

**Review by coltonhurst — APPROVED** [review]
Just a thought... When this is ready we may want to re-run `./support/build-api.sh` to verify these changes, and check if there are new changes we want to include or updates to non-SM items we need to include.

**Comment by Thomas-Avery** [comment]
Went ahead and regenerated the API bindings off of main, since this should be ready to go now. 

Most of the SM additional changes are coming from recent access policy endpoint updates. Since we don't use those endpoints in the SDK should be fine to bring in here.

**Review by coltonhurst — APPROVED** [review]

**Review by dani-garcia — APPROVED** [review]
LGTM! Bindings match with a local build

**Pull request merged**
